### ISSUE TITLE
Unused fields are not removed

### ISSUE THREAD

**Issue by Predelnik** [slycelote/caide-cpp-inliner#10]
Header:
```
#pragma once
struct C { using type = int; };
struct D { C::type v; };
```
And use only class `D` in actual code.

That's very simplified example but obviously it leads to inability to use any sort of your own type trait in library code.

**Comment by slycelote** [comment]
Does it only happen if the field `v` is unused?

**Comment by Predelnik** [comment]
Yeah it looks like assigning to `v` explicitly makes it work fine. Should this still work even if `v` is unused though because it doesn't get removed anyway?

**Comment by slycelote** [comment]
This should  be fixed now. (Although some unused fields still don't get removed, at least it won't cause compilation failure.)
