### ISSUE TITLE
run this project

### ISSUE THREAD

**Issue by WorldControl** [slycelote/caide-cpp-inliner#16]
Hi,after I build this project successfully,I don't know how to run the examples,I read the readme and some other files.I still not found how to use it.when I use `./cmd -std=c++11 -I . -isystem ../../src/clang/lib/Headers/ -- main.cpp ascii_graphics.cpp`,it turned out the error 
"error: no such file or directory: '/home/wc/gitHub/caide-cpp-inliner/doc/demo/caide-tmp/concat.cpp'
error: no input files
error: unable to handle compilation, expected exactly one compiler job in ''
Error while processing /home/wc/gitHub/caide-cpp-inliner/doc/demo/caide-tmp/concat.cpp.
Compilation error"
please help me

**Comment by slycelote** [comment]
Please create the directory `caide-tmp` before running the program.

**Comment by slycelote** [comment]
@WorldControl Did it help?
