### ISSUE TITLE
Used constructor is deleted

### ISSUE THREAD

**Issue by AlCash07** [slycelote/caide-cpp-inliner#4]
Here's an example where `range` constructor gets erroneously deleted [http://ideone.com/edb9hQ](http://ideone.com/edb9hQ). Interesting thing is that, if I remove `range` forward declaration, the constructor remains in place, but since `using base_type` is removed, it doesn't compile anyway.

**Comment by slycelote** [comment]
Constructor thing is fixed. However, as you mentioned, the whole example still won't work because of #3.
