### ISSUE TITLE
Build fails on XCode

### ISSUE THREAD

**Issue by AlCash07** [slycelote/caide-cpp-inliner#6]
I was going to check out the latest changes, so I updated the repo with submodules. Now I get the following compilation error on XCode:

In file included from /Users/oleksandr.bacherikov/caide-cpp-inliner/src/RemoveInactivePreprocessorBlocks.cpp:7:
/Users/oleksandr.bacherikov/caide-cpp-inliner/src/RemoveInactivePreprocessorBlocks.h:40:93: error: non-virtual member function marked 'override' hides virtual member function
    void MacroUndefined(const clang::Token& MacroNameTok, const clang::MacroDefinition& MD) override;
                                                                                            ^
In file included from /Users/oleksandr.bacherikov/caide-cpp-inliner/src/RemoveInactivePreprocessorBlocks.cpp:7:
In file included from /Users/oleksandr.bacherikov/caide-cpp-inliner/src/RemoveInactivePreprocessorBlocks.h:12:
/Users/oleksandr.bacherikov/caide-cpp-inliner/src/clang/include/clang/Lex/PPCallbacks.h:255:16: note: hidden overloaded virtual function 'clang::PPCallbacks::MacroUndefined' declared here: different number of parameters (3 vs 2)
  virtual void MacroUndefined(const Token &MacroNameTok,

Looks like some change was made in Clang in that function on April 27.

**Comment by slycelote** [comment]
Looks like you updated submodules to master or something like that. Type `git submodule update` to bring them back to the right commit.

**Comment by AlCash07** [comment]
Yes, that fixed it.
