### ISSUE TITLE
Complex macros are not supported

### ISSUE THREAD

**Issue by AlCash07** [slycelote/caide-cpp-inliner#7]
Most of the code gets removed, so the result doesn't compile [http://ideone.com/7yQH6L](http://ideone.com/7yQH6L)

**Comment by slycelote** [comment]
Multiline thing is unrelated, you'll get the same result if you put it all on a single line. The problem is that macros creating new declarations are generally unsupported. I may try to fix some simple cases, but no promise on that: macros, especially complex ones, are too rare.

**Comment by AlCash07** [comment]
Partial class creation using macros, probably, isn't a good style, and I'll rework that. But, in case there are a lot of similar functions, macros can really shorten the code, for example with [template point class](http://codeforces.com/blog/entry/48122). Looks like, the inliner works in that case. The only thing is that it leaves all the comments, for some reason.
